theme: minima
title: Dr. Cogan Shimizu
author:
  name: cogan-shimizu

show_downloads: false
minima:
  skin: solarized-light
  header_pages:
  - index.md
  - links.md
  - publications.md
  - activities.md
  - funding.md
  - cv.md
